name: First Workflow
on: [push, workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: 
          echo "Hello World"
          echo "Hello World 222"
      - name: Print a second step
        run: echo "Another Step"
      - name: Print a third step
        shell: python
        run: print("python Step")
