name: Second Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: npm-dep-${{ hashFiles('**/package-lock.json') }}

      - name: Get dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: List content
        run: ls -al
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: "http://localhost:5173"
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: npm-dep-${{ hashFiles('**/package-lock.json') }}

      - name: Get dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build the app
        run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pseudo Deployment
        run: echo "Deploying App"
